[package]
name = "bwinf41_zipper"
version = "0.1.0"
edition = "2021"
#default-run = "bwinf41_zipper"

[workspace]
members = ["bwinf41"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zip = "0.6.1"
zip-dir = "0.1.0"