[package]
name = "bwinf41-zipper"
version = "0.1.0"
edition = "2021"
default-run = "bwinf41-zipper"

[workspace]
members = ["bwinf41-1", "bwinf41-2"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zip = "0.6.1"
zip-dir = "0.1.0"