[package]
name = "bwinf41"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.6.0"
bit-vec = "0.6.3"
itertools = "0.10.3"
rayon = "1.5.3"